version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: longhall-mysql
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /home/ubuntu/Volumes/mysql:/var/lib/mysql
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: longhall-app
    ports:
      - 3001:3000
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
